baseURL = 'https://benjamin-philip.github.io/blog/'
languageCode = 'en-us'
title = "Ben's Untitled Blog"

[params]
  author = 'Benjamin Philip'
  description = "Ramblings and musings of a geeky, pessimistic, and Indian teenager."

[module]
[[module.imports]]
    path = 'github.com/spf13/hyde'
