baseURL = 'https://benjamin-philip.github.io/blog/'
languageCode = 'en-us'
title = "Ben's Untitled Blog"

[params]
  description = "Ramblings and musings of a geeky, pessimistic, and Indian teenager."

[params.license]
  name = "CC BY 4.0"
  link = "https://creativecommons.org/licenses/by/4.0/"

[menu]
  [[menu.main]]
    identifier = 'about'
    name = "About"
    url = '/about'
    weight = -110

  [[menu.main]]
    identifier = 'posts'
    name = "Posts"
    url = '/posts/'
    weight = -100

[author]
  name = "Benjamin Philip"
  email = "benjamin.philip495@gmail.com"

  [author.pgp]
    id = "foo"
    link = "bar"

  [author.socialmedia.github]
    username = "@Benjamin-Philip"
    link = "https://github.com/Benjamin-Philip"

  [author.socialmedia.gitlab]
    username = "@bphilip"
    link = "https://gitlab.com/bphilip"

  [author.socialmedia.mastodon]
    username = "@bphilip@fosstodon.org"
    link = "https://fosstodon.org/@bphilip"


[module]
[[module.imports]]
    path = 'github.com/Benjamin-Philip/burwell'

[markup.highlight]
  noClasses = false
